// <auto-generated />
using System;
using BookLibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BookLibraryApi.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "Douglas Adams",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(1979, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "Jane Austen",
                            Genre = "Romance",
                            PublishedDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Author = "Frank Herbert",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            PublishedDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Author = "Aldous Huxley",
                            Genre = "Dystopian",
                            PublishedDate = new DateTime(1932, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Author = "Charlotte Brontë",
                            Genre = "Romance",
                            PublishedDate = new DateTime(1847, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 3,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Author = "Ray Bradbury",
                            Genre = "Dystopian",
                            PublishedDate = new DateTime(1953, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Author = "Paulo Coelho",
                            Genre = "Fiction",
                            PublishedDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Author = "Andy Weir",
                            Genre = "Science Fiction",
                            PublishedDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Author = "Gillian Flynn",
                            Genre = "Thriller",
                            PublishedDate = new DateTime(2012, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Gone Girl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
